### PR TITLE
418

### PR DESCRIPTION
**Pull request by GuyKeogh**

### CODE REVIEW

**Comment by coillteoir** [comment]
Due to how the bot handles easter eggs, good night will be reacted to no matter what time of day it is.

It could be worth extending the logic of the bot to accommodate this. I do like the spooky scary halloween ones though :+1:

**Comment by GuyKeogh** [comment]
> Due to how the bot handles easter eggs, good night will be reacted to no matter what time of day it is.
> It could be worth extending the logic of the bot to accommodate this.

[But it's not a good night bot 🤣](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418)

**Comment by coillteoir** [comment]
Might be funny to have 418 be the easter egg

**Comment by coillteoir** [comment]
I drink tea at night so this is a win :+1:

**Review by coillteoir — APPROVED** [review]

**Pull request merged**
