### PR TITLE
added gifs

### PR DESCRIPTION
**Pull request by KeithSalhani**
They're hardcoded, would've preferred to use Giphy's API but I can't sign up at the moment

### CODE REVIEW

**Comment by coillteoir** [comment]
While there are some improvements in this PR that I'd like to see merged, I think that the gifs and good morning replies would add clutter to servers the bot is used in, maybe this could be reworked into the bot saying good morning and posting a gif at 6AM local time?

**Comment by KeithSalhani** [comment]
Yeah you're right, it'd be very cluttered. I Added weather, news, and video notifications for now and removed the gif replies.
It should now send an embed at 6 that looks like this.
image

You need API keys:
newsapi.org
weatherapi.com
developers.google.com/youtube/v3

**Comment by coillteoir** [comment]
Awesome work, I'll ask Ruan to run this fork for a couple of days to see it in action 👍

**Comment by RJMurg** [comment]
Keys were generated and inserted. Containerised through my PR and is now online.

**Comment by RJMurg** [comment]
I'm going to be a *massive* pedant, it's `Today's`.

**Comment by RJMurg** [comment]
Got an error,
```
023-07-01 06:30:59 ERROR    discord.ext.tasks Unhandled exception in internal background task 'send_message'.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/discord/ext/tasks/__init__.py", line 239, in _loop
    await self.coro(*args, **kwargs)
  File "/usr/src/MorningBot/bot.py", line 153, in send_message
    await channel.send(embed=embed)
          ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'send'
```

This meant the message never sent.

**Comment by KeithSalhani** [comment]
Did you set the channelID variable to the channelID?

**Comment by RJMurg** [comment]
I have added #the-terminal as the ChannelID.
We will see tomorrow.

**Comment by KeithSalhani** [comment]
Fixed bug, should now update information everyday instead of just at launch

**Comment by coillteoir** [comment]
Is it possible to remove the fireship video thing?

**Comment by KeithSalhani** [comment]
Yes, will be removed later today when I'm free. Also gonna fix up the news a bit because the titles are shit

**Comment by KeithSalhani** [comment]
Removed fireship vids, adjusted the news a bit, hopefully no more spammy headlines. If more spammy headlines appear I'll contain it to one site with good articles

**Comment by RJMurg** [comment]
Containerised and running.
I'll be Out-Of-Office very soon so if any other changes are going to be made I won't be able to deploy them.

**Comment by RJMurg** [comment]
Alright, everything is correctly set in `bot.py`.

**Comment by RJMurg** [comment]
All API keys correctly configured, discord channel ID is correct, all that is printed to the terminal is the following:
```
82.
4
5
gm detected > "Good morning." by irishtnt
````

No warnings, no errors, but also no morning message.

I will be out-of-office at 00:00 tomorrow, I will be unable to deploy any test changes after that point.

**Comment by RJMurg** [comment]
See #4 because of Docker.

**Comment by coillteoir** [comment]
LGTM :+1:

**Pull request merged**
